name: sweep-collab-dense-2
method: bayes  # 'random' or 'grid' are alternatives
metric:
  name: val_top_1_accuracy
  goal: maximize

parameters:
  learning_rate:
    distribution: uniform
    min: 0.002
    max: 0.009
  weight_decay:
    distribution: uniform
    min: 1e-5
    max: 1e-3
  momentum:
    max: 0.99
    min: 0.8
    distribution: uniform
  label_smoothing:
    max: 0.2
    min: 0.0
    distribution: uniform
  batch_size:
    values: [256, 384, 512]
  val_split:
    values: [0.1]
  epochs:
    value: 10
  num_workers:
    value: 4


early_terminate:
  type: hyperband
  min_iter: 5

command:
  - python
  - train.py
