name: sweep-local
method: bayes  # 'random' or 'grid' are alternatives
metric:
  name: val_top_1_accuracy
  goal: maximize

parameters:
  learning_rate:
    distribution: log_uniform_values
    min: 0.00001
    max: 0.01
  weight_decay:
    values: [0.0001, 0.001, 0.01]
  momentum:
    values: [0.8, 0.9, 0.95]
  batch_size:
    values: [32, 64, 128, 256]
  val_split:
    values: [0.05, 0.1, 0.2]
  epochs:
    value: 10
  num_workers:
    value: 4

early_terminate:
  type: hyperband
  min_iter: 5

command:
  - C:\Users\Atabay\PycharmProjects\DLML_FL_project\.venv\Scripts\python.exe
  - train_centralized.py
